# Generated by Django 2.0.6 on 2018-06-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
